In [47]:
import numpy as np
m = 128
n = 128
p = 128

test_a = np.zeros((m, n))
test_b = np.ones((n, p))

for i in range(m):
    for j in range(n):
        test_a[i][j] = i*n+j

# init test_b array from 0 to 255
for i in range(n):
    for j in range(p):
        test_b[i][j] = i*p+j

In [48]:
print(test_a)

[[0.0000e+00 1.0000e+00 2.0000e+00 ... 1.2500e+02 1.2600e+02 1.2700e+02]
 [1.2800e+02 1.2900e+02 1.3000e+02 ... 2.5300e+02 2.5400e+02 2.5500e+02]
 [2.5600e+02 2.5700e+02 2.5800e+02 ... 3.8100e+02 3.8200e+02 3.8300e+02]
 ...
 [1.6000e+04 1.6001e+04 1.6002e+04 ... 1.6125e+04 1.6126e+04 1.6127e+04]
 [1.6128e+04 1.6129e+04 1.6130e+04 ... 1.6253e+04 1.6254e+04 1.6255e+04]
 [1.6256e+04 1.6257e+04 1.6258e+04 ... 1.6381e+04 1.6382e+04 1.6383e+04]]


In [49]:
print(test_b)

[[0.0000e+00 1.0000e+00 2.0000e+00 ... 1.2500e+02 1.2600e+02 1.2700e+02]
 [1.2800e+02 1.2900e+02 1.3000e+02 ... 2.5300e+02 2.5400e+02 2.5500e+02]
 [2.5600e+02 2.5700e+02 2.5800e+02 ... 3.8100e+02 3.8200e+02 3.8300e+02]
 ...
 [1.6000e+04 1.6001e+04 1.6002e+04 ... 1.6125e+04 1.6126e+04 1.6127e+04]
 [1.6128e+04 1.6129e+04 1.6130e+04 ... 1.6253e+04 1.6254e+04 1.6255e+04]
 [1.6256e+04 1.6257e+04 1.6258e+04 ... 1.6381e+04 1.6382e+04 1.6383e+04]]


In [50]:
print(test_b[:, 0])

[    0.   128.   256.   384.   512.   640.   768.   896.  1024.  1152.
  1280.  1408.  1536.  1664.  1792.  1920.  2048.  2176.  2304.  2432.
  2560.  2688.  2816.  2944.  3072.  3200.  3328.  3456.  3584.  3712.
  3840.  3968.  4096.  4224.  4352.  4480.  4608.  4736.  4864.  4992.
  5120.  5248.  5376.  5504.  5632.  5760.  5888.  6016.  6144.  6272.
  6400.  6528.  6656.  6784.  6912.  7040.  7168.  7296.  7424.  7552.
  7680.  7808.  7936.  8064.  8192.  8320.  8448.  8576.  8704.  8832.
  8960.  9088.  9216.  9344.  9472.  9600.  9728.  9856.  9984. 10112.
 10240. 10368. 10496. 10624. 10752. 10880. 11008. 11136. 11264. 11392.
 11520. 11648. 11776. 11904. 12032. 12160. 12288. 12416. 12544. 12672.
 12800. 12928. 13056. 13184. 13312. 13440. 13568. 13696. 13824. 13952.
 14080. 14208. 14336. 14464. 14592. 14720. 14848. 14976. 15104. 15232.
 15360. 15488. 15616. 15744. 15872. 16000. 16128. 16256.]


In [51]:
print(test_a @ test_b)

[[8.84326400e+07 8.84407680e+07 8.84488960e+07 ... 8.94486400e+07
  8.94567680e+07 8.94648960e+07]
 [2.21601792e+08 2.21626304e+08 2.21650816e+08 ... 2.24665792e+08
  2.24690304e+08 2.24714816e+08]
 [3.54770944e+08 3.54811840e+08 3.54852736e+08 ... 3.59882944e+08
  3.59923840e+08 3.59964736e+08]
 ...
 [1.67345766e+10 1.67366328e+10 1.67386889e+10 ... 1.69915926e+10
  1.69936488e+10 1.69957049e+10]
 [1.68677458e+10 1.68698183e+10 1.68718908e+10 ... 1.71268098e+10
  1.71288823e+10 1.71309548e+10]
 [1.70009149e+10 1.70030038e+10 1.70050927e+10 ... 1.72620269e+10
  1.72641158e+10 1.72662047e+10]]
